class_name Loc
extends Object

const SETTINGS_PATH := "user://cluck-settings.json"

static var lang := "zh"
static var ui_font_scale := 0.85
static var _booted := false
static var _toggle_ms := 0

const ZH := {
	"settings": "设置",
	"font_size": "字体大小",
	"font_small": "小",
	"font_standard": "标准",
	"font_large": "大",
	"close": "关闭",
	"sfx_on": "音效：开",
	"sfx_off": "音效：关",
	"amb_on": "环境音：开",
	"amb_off": "环境音：关",
	"sfx_title": "音效",
	"amb_title": "环境音",
	"toggle_on": "开",
	"toggle_off": "关",
	"help": "只点气泡和按钮。长按可以连续收、买、卖。八日挑战：资产 3000，同时养 15 只鸡。",
	"credits": "制作人：hhhhhnicaia@gmail.com",
	"restart": "重置游戏",
	"home_menu": "返回主菜单",
	"tutorial_replay": "重玩新手关",
	"guide": "新手攻略",
	"guide_title": "小鸡股市 · 一日入门",
	"guide_subtitle": "一天学完农场和股市",
	"guide_step_eggs": "1  收蛋",
	"guide_step_eggs_desc": "母鸡会生蛋，时间不固定。蛋出来后要点气泡收下。",
	"guide_step_chick": "2  孵化与蛋糕",
	"guide_step_chick_desc": "每天最多 1 个蛋进鸟窝，第二天孵成小鸡。2 个蛋烤成蛋糕，收下得 150 金币。",
	"guide_step_stock": "3  买鸡与股票",
	"guide_step_stock_desc": "50 金币买一只鸡，第二天才生蛋。多余的钱买股票，股价每天随机涨跌，卖比买高就赚。8 天内达到 3000 金币和 15 只鸡。",
	"tutorial_header": "一日入门",
	"tutorial_day_frac": "教学",
	"tutorial_exit": "退出教学",
	"tutorial_begin": "开始",
	"tutorial_continue": "继续",
	"tutorial_finish": "进入正式游戏",
	"tutorial_t0_goal": "目标：8 天内攒到 3000 金币，并养到 15 只鸡。教学期间时间暂停。",
	"tutorial_t1_eggs": "母鸡会生蛋，但时间不固定。蛋出来后，点气泡收下。（%d/3）",
	"tutorial_t1_eggs_landing": "蛋正在飞进篮子，稍等。（%d/3）",
	"tutorial_t2_hatch": "每天最多把 1 个蛋放进鸟窝，第二天孵成小鸡。点孵化。",
	"tutorial_t3_cake_wait": "剩下 2 个蛋会在烘焙坊自动烤成蛋糕，稍等。",
	"tutorial_t3_cake_sell": "点蛋糕，直接换成 150 金币。",
	"tutorial_t4_hen": "花 50 金币买一只鸡。买来的鸡第二天才生蛋。",
	"tutorial_t5_buy": "多余的钱可以买股票。股价每天随机涨跌。先买 1 股。",
	"tutorial_t6_sell": "假如过了一夜，股价从 120 涨到 150。卖出比买入高，就赚到了。",
	"tutorial_t7_done": "收蛋、孵鸡、烤蛋糕、买鸡、做股票。去完成 8 日目标吧。",
	"tutorial_tap_hint": "请点击画面中金色跳动的目标。",
	"tutorial_locked_hint": "其余操作稍后解锁。",
	"tutorial_exit_toast": "已退出教学",
	"tutorial_complete_toast": "入门完成！正式八日挑战开始",
	"start_pick": "选一个开始",
	"start_tutorial": "新手教程",
	"start_direct": "开始游戏",
	"start_endless": "无尽模式",
	"start_settings": "设置",
	"start_trophies": "成就",
	"day_endless": "第 %d 天",
	"trophy_title": "成就",
	"trophy_locked": "尚未解锁",
	"toast_trophy": "成就解锁：%s",
	"trophy_primer": "一日入门",
	"trophy_primer_desc": "学完收蛋、孵化、烤蛋糕和买卖。",
	"trophy_cake": "第一块蛋糕",
	"trophy_cake_desc": "把烤好的蛋糕换成金币。",
	"trophy_hen": "鸡舍开张",
	"trophy_hen_desc": "从狼摊买来第一只鸡。",
	"trophy_share": "进场交易",
	"trophy_share_desc": "买下第一股。",
	"trophy_rank_day8_desc": "八日收官时资产达到 %d。",
	"trophy_rank_endless_desc": "无尽模式资产达到 %d。",
	"trophy_flock": "十五只鸡",
	"trophy_flock_desc": "同时养到 15 只鸡。",
	"trophy_day8": "八日收官",
	"trophy_day8_desc": "打完一局八日挑战。",
	"trophy_endless7": "无尽七日",
	"trophy_endless7_desc": "无尽模式活到第 7 天。",
	"trophy_chicken_king": "鸡王",
	"trophy_chicken_king_desc": "同时养到 100 只鸡。",
	"trophy_chicken_emperor": "鸡王之王",
	"trophy_chicken_emperor_desc": "同时养到 1000 只鸡。",
	"trophy_retail": "谁说散户就是韭菜",
	"trophy_retail_desc": "一局里股票增值达到 2000。",
	"trophy_stock_god": "炒股大神",
	"trophy_stock_god_desc": "一局里股票增值达到 3000。",
	"lang": "English / 中文",
	"language": "语言",
	"lang_zh": "语言：中文",
	"lang_en": "Language: English",
	"cash": "现金",
	"stock": "股票",
	"day_frac": "%d/8天",
	"end_day": "结束今天",
	"dusk_warn": "天快黑了",
	"buy_chick": "买\n%d",
	"sell_hen": "卖\n%d",
	"buy_share": "买入",
	"sell_share": "卖出",
	"eggs_count": "蛋 %d",
	"oven_max": "Lv.%d 已满",
	"oven_up": "↑ Lv.%d→%d · %d",
	"gold_n": "金币  %d",
	"shares_n": "持有 %d 股",
	"price_cap": "当前股价",
	"hold_hint": "长按可连续操作",
	"baking": "烘焙中 %.1fs",
	"sell_cake_tip": "出售蛋糕，现有 %d 个",
	"cake_baking_tip": "蛋糕制作中",
	"news_hoard": "狼商囤粮",
	"news_cake": "蛋糕热销",
	"news_rain": "雨天减产",
	"tonight_news": "今夜告示 · %s",
	"quest_head": "农场任务",
	"quest_goal": "资产 3000，同时养 15 只鸡",
	"quest_done": "同一时刻双线达标",
	"quest_wealth": "总资产 %d / %d",
	"quest_flock": "拥有鸡 %d / %d",
	"quest_wealth_name": "总资产",
	"quest_flock_name": "拥有鸡",
	"quest_need_gold": "还差 %d",
	"quest_need_birds": "还差 %d 只",
	"quest_hit": "已达标",
	"quest_note": "两项要同时达到。资产掉下去或把鸡卖掉，完成会取消。",
	"quest_note_done": "三千金币和十五只鸡，同一时刻到手。",
	"toast_dusk": "天快黑了，蛋会碎！",
	"toast_eggs_done": "今天的鸡蛋已经收完啦",
	"toast_no_chick": "还没有孵出来的小鸡",
	"toast_hatch_once": "每天只能孵 1 枚蛋",
	"toast_need_egg": "还差鸡蛋",
	"toast_hatching": "放进孵蛋器啦，明天出壳",
	"toast_no_cake": "还没有可出售的蛋糕",
	"toast_need_gold_share": "金币不够买入一股",
	"toast_no_shares": "还没有持股",
	"toast_need_gold_chick": "金币不够买小鸡",
	"toast_oven_short": "升级烤炉还差 %d 金币",
	"toast_oven_up": "烤炉升到 Lv.%d · 制作只需 %.1f 秒",
	"toast_no_hen": "还没有可以卖的母鸡",
	"toast_eggs_lost": "今天的蛋没有留到明天",
	"toast_no_rewind": "这一天没法重玩",
	"toast_watching_ad": "正在招商…",
	"toast_rewound": "已重玩第 %d 天",
	"toast_quest": "双线达标！",
	"daily_title": "今日结算",
	"report_stats": "本日账目",
	"day_to_day": "第 %d 天  →  第 %d 天",
	"night_n": "第 %d 夜",
	"close_price": "收盘股价",
	"broken": "碎蛋",
	"grown": "长成",
	"cakes": "蛋糕",
	"wealth_flow": "总资产  %d  →  %d",
	"hatch_note": "新孵 %d 只，天亮后领取",
	"start_new_day": "开始新一天",
	"watch_ad": "看广告回到清晨",
	"finale_title": "八日总结",
	"finale_hook": "我在八日挑战里混成了",
	"rank_n": "第 %d / %d 等",
	"wealth_cap": "总资产",
	"flock_cap": "鸡群",
	"birds_n": "%d 只",
	"goal_n": "目标 %d",
	"goal_frac": "%d / %d",
	"goal_gap": "还差 %d",
	"goal_over": "多出 %d",
	"goal_over_gold": "多出 %d 金币",
	"goal_over_birds": "多出 %d 只鸡",
	"goal_gap_gold": "还差 %d 金币",
	"quest_stamp": "双线达标",
	"quest_miss": "未达标",
	"wealth_split": "现金 %d + 股票 %d",
	"chart_cap": "八日资产",
	"chart_goal": "目标 %d",
	"retry_eight": "再挑战八天",
	"continue_endless": "继续无尽模式",
	"share_card": "分享成绩",
	"share_saved": "已保存",
	"share_mark": "小鸡股市 · 敢不敢比",
	"toast_card_saved": "成绩图已保存，发到聊天里晒一下",
	"toast_card_fail": "图片没存下来，再试一次",
	"beat_daily": "你打败了 %s%% 的农场主。%s",
	"beat_finale": "八日收官，你打败了 %s%% 的挑战者。%s",
	"beat_tail_0": "才刚进场，明天再捞。",
	"beat_tail_1": "超过了一小撮人。",
	"beat_tail_2": "有点东西了。",
	"beat_tail_3": "快摸到中位了。",
	"beat_tail_4": "太厉害了！",
	"beat_tail_5": "这局有点离谱。",
	"beat_tail_6": "这局封神了！",
	"rank_1_title": "流浪小鸡",
	"rank_1_copy": "八天空手而归。鸡：这人我都不认识。",
	"rank_2_title": "见习农民",
	"rank_2_copy": "刚摸到锄头，蛋还得自己捡。",
	"rank_3_title": "咯咯佃农",
	"rank_3_copy": "农场转了，钱包没转。",
	"rank_4_title": "篱笆鸡舍",
	"rank_4_copy": "篱笆围上了，蛋篓开始像样。",
	"rank_5_title": "积谷农户",
	"rank_5_copy": "谷仓有底，离顿顿吃饱还差一口。",
	"rank_6_title": "温饱农场",
	"rank_6_copy": "八日攒到三千，桌上终于能摆上热饭。",
	"rank_7_title": "街口商贩",
	"rank_7_copy": "四千二出手，邻居开始打听你。",
	"rank_8_title": "农场掌柜",
	"rank_8_copy": "五千二。鸡舍和股市两边都能转。",
	"rank_9_title": "金币大亨",
	"rank_9_copy": "六千五进袋，街坊开始叫你大亨。",
	"rank_10_title": "农场传奇",
	"rank_10_copy": "八千封顶。八日能摸到的最高等。",
	"rank_11_title": "农场街新贵",
	"rank_11_copy": "无尽里把家业推到一万三，街上换你的名。",
	"rank_12_title": "鸡隆·股斯克",
	"rank_12_copy": "一万八。鸡界本隆，股斯克本人。",
}

const EN := {
	"settings": "Settings",
	"font_size": "Text Size",
	"font_small": "Small",
	"font_standard": "Default",
	"font_large": "Large",
	"close": "Close",
	"sfx_on": "SFX: On",
	"sfx_off": "SFX: Off",
	"amb_on": "Ambience: On",
	"amb_off": "Ambience: Off",
	"sfx_title": "Sound Effects",
	"amb_title": "Ambient Sound",
	"toggle_on": "On",
	"toggle_off": "Off",
	"help": "Tap bubbles and buttons. Hold to collect, buy, or sell. 8-day challenge: 3000 wealth and 15 birds at once.",
	"credits": "Contact: hhhhhhnicaia@gmail.com",
	"restart": "Reset Game",
	"home_menu": "Main Menu",
	"tutorial_replay": "Replay Tutorial",
	"guide": "Quick Guide",
	"guide_title": "Chicken Market · One-Day Primer",
	"guide_subtitle": "Learn the farm and the market in one sitting",
	"guide_step_eggs": "1  Collect Eggs",
	"guide_step_eggs_desc": "Hens lay on their own clock. When an egg appears, tap the bubble to collect it.",
	"guide_step_chick": "2  Hatch and Bake",
	"guide_step_chick_desc": "At most one egg goes in the nest each day and hatches tomorrow. Two eggs bake into a cake worth 150 gold.",
	"guide_step_stock": "3  Hens and Stocks",
	"guide_step_stock_desc": "A hen costs 50 and lays starting tomorrow. Spare gold can buy stock; the price moves each day. Sell higher than you bought to profit. Hit 3000 gold and 15 birds in 8 days.",
	"tutorial_header": "One-Day Primer",
	"tutorial_day_frac": "Lesson",
	"tutorial_exit": "Exit Tutorial",
	"tutorial_begin": "Start",
	"tutorial_continue": "Continue",
	"tutorial_finish": "Start the Real Game",
	"tutorial_t0_goal": "Goal: reach 3000 gold and 15 birds within 8 days. Time is paused during the lesson.",
	"tutorial_t1_eggs": "Hens lay eggs, but not on a fixed timer. When one appears, tap the bubble. (%d/3)",
	"tutorial_t1_eggs_landing": "The eggs are flying to the basket. Wait a moment. (%d/3)",
	"tutorial_t2_hatch": "You can nest at most 1 egg per day. It hatches into a chick tomorrow. Tap hatch.",
	"tutorial_t3_cake_wait": "The other 2 eggs bake into a cake automatically. Wait for it.",
	"tutorial_t3_cake_sell": "Tap the cake to turn it into 150 gold.",
	"tutorial_t4_hen": "Spend 50 gold to buy a hen. She only starts laying tomorrow.",
	"tutorial_t5_buy": "Spare gold can buy stock. The price moves at random each day. Buy 1 share.",
	"tutorial_t6_sell": "Pretend a night passed: the price rose from 120 to 150. Sell higher than you bought to profit.",
	"tutorial_t7_done": "Collect, hatch, bake, buy hens, trade stock. Now go hit the 8-day goal.",
	"tutorial_tap_hint": "Tap the gold pulsing target.",
	"tutorial_locked_hint": "The other actions unlock next.",
	"tutorial_exit_toast": "Tutorial closed.",
	"tutorial_complete_toast": "Primer done! The real 8-day challenge begins.",
	"start_pick": "Pick a start",
	"start_tutorial": "Tutorial",
	"start_direct": "Start Game",
	"start_endless": "Endless",
	"start_settings": "Settings",
	"start_trophies": "Trophies",
	"day_endless": "Day %d",
	"trophy_title": "Trophies",
	"trophy_locked": "Locked",
	"toast_trophy": "Trophy: %s",
	"trophy_primer": "One-Day Primer",
	"trophy_primer_desc": "Finish collect, hatch, bake, and trade.",
	"trophy_cake": "First Cake",
	"trophy_cake_desc": "Sell a baked cake for gold.",
	"trophy_hen": "Coop Open",
	"trophy_hen_desc": "Buy your first hen from the wolf.",
	"trophy_share": "First Trade",
	"trophy_share_desc": "Buy your first share.",
	"trophy_rank_day8_desc": "Hit %d wealth at the 8-day close.",
	"trophy_rank_endless_desc": "Hit %d wealth in Endless.",
	"trophy_flock": "Fifteen Birds",
	"trophy_flock_desc": "Hold 15 birds at once.",
	"trophy_day8": "Eight-Day Close",
	"trophy_day8_desc": "Finish an 8-day challenge.",
	"trophy_endless7": "Endless Seven",
	"trophy_endless7_desc": "Reach day 7 in Endless.",
	"trophy_chicken_king": "Chicken King",
	"trophy_chicken_king_desc": "Hold 100 birds at once.",
	"trophy_chicken_emperor": "Chicken Emperor",
	"trophy_chicken_emperor_desc": "Hold 1000 birds at once.",
	"trophy_retail": "Retail Isn't Chives",
	"trophy_retail_desc": "Make 2000 from stocks in one run.",
	"trophy_stock_god": "Stock God",
	"trophy_stock_god_desc": "Make 3000 from stocks in one run.",
	"lang": "English / 中文",
	"language": "Language",
	"lang_zh": "语言：中文",
	"lang_en": "Language: English",
	"cash": "Cash",
	"stock": "Stocks",
	"day_frac": "Day %d/8",
	"end_day": "End Today",
	"dusk_warn": "Night falling",
	"buy_chick": "Buy\n%d",
	"sell_hen": "Sell\n%d",
	"buy_share": "Buy",
	"sell_share": "Sell",
	"eggs_count": "Eggs %d",
	"oven_max": "Lv.%d max",
	"oven_up": "↑ Lv.%d→%d · %d",
	"gold_n": "Gold  %d",
	"shares_n": "Holding %d",
	"price_cap": "Price Now",
	"hold_hint": "Hold to repeat",
	"baking": "Baking %.1fs",
	"sell_cake_tip": "Sell cakes (%d)",
	"cake_baking_tip": "Cake in the oven",
	"news_hoard": "Wolf hoards",
	"news_cake": "Cake boom",
	"news_rain": "Rain cut",
	"tonight_news": "Tonight · %s",
	"quest_head": "Farm Quest",
	"quest_goal": "Hit 3000 wealth and 15 birds at the same time",
	"quest_done": "Both goals met",
	"quest_wealth": "Wealth %d / %d",
	"quest_flock": "Birds %d / %d",
	"quest_wealth_name": "Wealth",
	"quest_flock_name": "Birds",
	"quest_need_gold": "%d to go",
	"quest_need_birds": "%d birds to go",
	"quest_hit": "Done",
	"quest_note": "Both must be true at the same time. Selling birds or losing wealth undoes it.",
	"quest_note_done": "3000 gold and 15 birds, held together.",
	"toast_dusk": "Night is falling — eggs will spoil!",
	"toast_eggs_done": "No more eggs today",
	"toast_no_chick": "No chicks have hatched yet",
	"toast_hatch_once": "Only 1 egg can hatch per day",
	"toast_need_egg": "Need an egg first",
	"toast_hatching": "In the incubator — hatches tomorrow",
	"toast_no_cake": "No cakes to sell",
	"toast_need_gold_share": "Not enough gold for a share",
	"toast_no_shares": "You don't hold any shares",
	"toast_need_gold_chick": "Not enough gold for a chick",
	"toast_oven_short": "Need %d more gold to upgrade",
	"toast_oven_up": "Oven Lv.%d · bakes in %.1fs",
	"toast_no_hen": "No hens to sell",
	"toast_eggs_lost": "Today's eggs didn't last the night",
	"toast_no_rewind": "Can't rewind this day",
	"toast_watching_ad": "Ads coming soon…",
	"toast_rewound": "Rewound to day %d",
	"toast_quest": "Both goals hit!",
	"daily_title": "Daily Close",
	"report_stats": "Today",
	"day_to_day": "Day %d → %d",
	"night_n": "Night %d",
	"close_price": "Close",
	"broken": "Break",
	"grown": "Grown",
	"cakes": "Cake",
	"wealth_flow": "Wealth  %d → %d",
	"hatch_note": "%d hatched · collect at dawn",
	"start_new_day": "Start new day",
	"watch_ad": "Ad → rewind to dawn",
	"finale_title": "8-Day Summary",
	"finale_hook": "My 8-day rank:",
	"rank_n": "Rank %d / %d",
	"wealth_cap": "Wealth",
	"flock_cap": "Flock",
	"birds_n": "%d birds",
	"goal_n": "Goal %d",
	"goal_frac": "%d / %d",
	"goal_gap": "%d short",
	"goal_over": "+%d",
	"goal_over_gold": "+%d gold",
	"goal_over_birds": "+%d birds",
	"goal_gap_gold": "%d gold short",
	"quest_stamp": "Both goals hit",
	"quest_miss": "Not cleared",
	"wealth_split": "Cash %d + Stock %d",
	"chart_cap": "8-day wealth",
	"chart_goal": "Goal %d",
	"retry_eight": "Try 8 days again",
	"continue_endless": "Continue Endless",
	"share_card": "Share",
	"share_saved": "Saved",
	"share_mark": "Chick Street · beat me",
	"toast_card_saved": "Card saved. Post it.",
	"toast_card_fail": "Couldn't save. Try again.",
	"beat_daily": "You beat %s%% of farms. %s",
	"beat_finale": "Eight-day close: you beat %s%% of challengers. %s",
	"beat_tail_0": "Just getting started.",
	"beat_tail_1": "A sliver ahead.",
	"beat_tail_2": "Not bad at all.",
	"beat_tail_3": "Almost at the median.",
	"beat_tail_4": "That's strong!",
	"beat_tail_5": "This run is wild.",
	"beat_tail_6": "This run is cracked!",
	"rank_1_title": "Stray Chick",
	"rank_1_copy": "Eight days. Empty pockets. The hens don't know you.",
	"rank_2_title": "Apprentice Farmer",
	"rank_2_copy": "Just found the hoe. Still picking eggs yourself.",
	"rank_3_title": "Cluck Tenant",
	"rank_3_copy": "Farm's running. Wallet isn't.",
	"rank_4_title": "Fence Coop",
	"rank_4_copy": "Fence is up. The egg basket looks real.",
	"rank_5_title": "Grain Farmer",
	"rank_5_copy": "The barn has a floor. Full meals are still a bite away.",
	"rank_6_title": "Full-Belly Farm",
	"rank_6_copy": "Three thousand in eight days. Dinner is hot.",
	"rank_7_title": "Corner Vendor",
	"rank_7_copy": "Forty-two hundred. Neighbors started asking.",
	"rank_8_title": "Farm Keeper",
	"rank_8_copy": "Fifty-two hundred. Coop and market both run.",
	"rank_9_title": "Gold Baron",
	"rank_9_copy": "Sixty-five hundred. They started calling you baron.",
	"rank_10_title": "Farm Legend",
	"rank_10_copy": "Eight thousand. The top of the eight-day climb.",
	"rank_11_title": "Farm Street Star",
	"rank_11_copy": "Thirteen thousand in Endless. The street says your name.",
	"rank_12_title": "Clucklon Musk",
	"rank_12_copy": "Eighteen thousand. Clucklon Musk of Chicken Street.",
}

static func t(key: String, args: Array = []) -> String:
	if not _booted:
		_booted = true
		load_settings()
	var table: Dictionary = EN if lang == "en" else ZH
	var s := str(table.get(key, ZH.get(key, key)))
	if args.is_empty():
		return s
	return s % args

static func news(id: String) -> String:
	return t("news_%s" % id)

static func rank_title(lv: int) -> String:
	return t("rank_%d_title" % clampi(lv, 1, 12))

static func rank_copy(lv: int) -> String:
	return t("rank_%d_copy" % clampi(lv, 1, 12))

static func toggle() -> void:
	var now := Time.get_ticks_msec()
	if now - _toggle_ms < 280:
		return
	_toggle_ms = now
	lang = "en" if lang == "zh" else "zh"
	save()

static func load_settings() -> void:
	if not FileAccess.file_exists(SETTINGS_PATH):
		return
	var f := FileAccess.open(SETTINGS_PATH, FileAccess.READ)
	if f == null:
		return
	var parsed = JSON.parse_string(f.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY:
		return
	var next := str(parsed.get("lang", lang))
	if next == "en" or next == "zh":
		lang = next
	ui_font_scale = 0.85

static func set_ui_font_scale(value: float) -> void:
	ui_font_scale = clampf(value, 0.85, 1.15)
	save()

static func save() -> void:
	var f := FileAccess.open(SETTINGS_PATH, FileAccess.WRITE)
	if f:
		f.store_string(JSON.stringify({"lang": lang, "ui_font_scale": ui_font_scale}))
