class_name Loc
extends Object

const SETTINGS_PATH := "user://cluck-settings.json"

static var lang := "en"
static var ui_font_scale := 0.85
static var _booted := false
static var _toggle_ms := 0

const ZH := {
	"challenge_goal": "第 %d 天收盘：资产 %d，鸡群 %d",
	"challenge_ready": "当前达标，收盘时确认。",
	"challenge_pending": "收盘时两项须同时达标。",
	"challenge_rules": "本阶段每天 %d 秒，买鸡 %d 金币。",
	"challenge_summary": "挑战总结",
	"challenge_hook": "本次挑战成绩",
	"challenge_chart": "挑战资产曲线",
	"settings": "设置",
	"font_size": "字体大小",
	"font_small": "小",
	"font_standard": "标准",
	"font_large": "大",
	"close": "关闭",
	"sfx_on": "音效：开",
	"sfx_off": "音效：关",
	"amb_on": "环境音：开",
	"amb_off": "环境音：关",
	"sfx_title": "音效",
	"amb_title": "环境音",
	"toggle_on": "开",
	"toggle_off": "关",
	"help": "只点气泡和按钮。长按可以连续收、买、卖。八日挑战：资产 3000，同时养 15 只鸡。",
	"credits": "制作人：hhhhhnicaia@gmail.com",
	"restart": "重置游戏",
	"home_menu": "返回主菜单",
	"tutorial_replay": "重玩新手关",
	"guide": "新手攻略",
	"guide_title": "小鸡股市 · 一日入门",
	"guide_subtitle": "一天学完农场和股市",
	"guide_step_eggs": "1  收蛋",
	"guide_step_eggs_desc": "母鸡会生蛋，时间不固定。蛋出来后要点气泡收下。",
	"guide_step_chick": "2  孵化与蛋糕",
	"guide_step_chick_desc": "每天最多 1 个蛋进鸟窝，第二天孵成小鸡。2 个蛋烤成蛋糕，收下得 150 金币。",
	"guide_step_stock": "3  买鸡与股票",
	"guide_step_stock_desc": "50 金币买一只鸡，第二天才生蛋。多余的钱买股票，股价每天随机涨跌，卖比买高就赚。8 天内达到 3000 金币和 15 只鸡。",
	"tutorial_header": "一日入门",
	"tutorial_day_frac": "教学",
	"tutorial_exit": "退出教学",
	"tutorial_begin": "开始",
	"tutorial_continue": "继续",
	"tutorial_finish": "进入正式游戏",
	"tutorial_t0_goal": "目标：8 天内攒到 3000 金币，并养到 15 只鸡。教学期间时间暂停。",
	"tutorial_t1_eggs": "母鸡会生蛋，但时间不固定。蛋出来后，点气泡收下。（%d/3）",
	"tutorial_t1_eggs_landing": "蛋正在飞进篮子，稍等。（%d/3）",
	"tutorial_t2_hatch": "每天最多把 1 个蛋放进鸟窝，第二天孵成小鸡。点孵化。",
	"tutorial_t3_cake_wait": "剩下 2 个蛋会在烘焙坊自动烤成蛋糕，稍等。",
	"tutorial_t3_cake_sell": "点蛋糕，直接换成 150 金币。",
	"tutorial_t4_hen": "花 50 金币买一只鸡。买来的鸡第二天才生蛋。",
	"tutorial_t5_buy": "多余的钱可以买股票。股价每天随机涨跌。先买 1 股。",
	"tutorial_t6_sell": "假如过了一夜，股价从 120 涨到 150。卖出比买入高，就赚到了。",
	"tutorial_t7_done": "收蛋、孵鸡、烤蛋糕、买鸡、做股票。去完成 8 日目标吧。",
	"tutorial_tap_hint": "请点击画面中金色跳动的目标。",
	"tutorial_locked_hint": "其余操作稍后解锁。",
	"tutorial_exit_toast": "已退出教学",
	"tutorial_complete_toast": "入门完成！正式八日挑战开始",
	"start_pick": "选一个开始",
	"start_tutorial": "新手教程",
	"start_direct": "开始游戏",
	"start_challenge": "挑战模式",
	"start_endless": "无尽模式",
	"toast_lock_challenge": "先打完八日收官",
	"toast_lock_endless": "先过挑战第20天",
	"you_win": "你赢了",
	"back_menu": "回菜单",
	"enter_challenge": "进入挑战",
	"retry_challenge": "再试挑战",
	"challenge_flop_copy": "第 %d 天门槛没过。",
	"campaign_flop_copy": "八日目标没过：3000 金币和 15 只鸡。",
	"start_settings": "设置",
	"start_trophies": "成就",
	"day_endless": "第 %d 天",
	"trophy_title": "成就",
	"trophy_locked": "尚未解锁",
	"toast_trophy": "成就解锁：%s",
	"trophy_primer": "一日入门",
	"trophy_primer_desc": "学完收蛋、孵化、烤蛋糕和买卖。",
	"trophy_cake": "第一块蛋糕",
	"trophy_cake_desc": "把烤好的蛋糕换成金币。",
	"trophy_hen": "鸡舍开张",
	"trophy_hen_desc": "从狼摊买来第一只鸡。",
	"trophy_share": "进场交易",
	"trophy_share_desc": "买下第一股。",
	"trophy_rank_day8_desc": "八日收官时资产达到 %d。",
	"trophy_rank_endless_desc": "无尽模式资产达到 %d。",
	"trophy_flock": "十五只鸡",
	"trophy_flock_desc": "同时养到 15 只鸡。",
	"trophy_day8": "八日收官",
	"trophy_day8_desc": "打完一局八日挑战。",
	"trophy_endless7": "无尽七日",
	"trophy_endless7_desc": "无尽模式活到第 7 天。",
	"trophy_chicken_king": "鸡王",
	"trophy_chicken_king_desc": "同时养到 100 只鸡。",
	"trophy_chicken_emperor": "鸡王之王",
	"trophy_chicken_emperor_desc": "同时养到 200 只鸡。",
	"trophy_retail": "谁说散户就是韭菜",
	"trophy_retail_desc": "一局里股票增值达到 2000。",
	"trophy_stock_god": "炒股大神",
	"trophy_stock_god_desc": "一局里股票增值达到 3000。",
	"trophy_wealth_tier_desc": "挑战通关时资产达到 %d。",
	"trophy_wealth_100k": "封鸡隆·股斯克",
	"trophy_wealth_90k": "90,000",
	"trophy_wealth_80k": "鸡伦·巴菲特",
	"trophy_wealth_70k": "70,000",
	"trophy_wealth_60k": "60,000",
	"trophy_wealth_50k": "50,000",
	"trophy_wealth_40k": "40,000",
	"trophy_wealth_30k": "30,000",
	"trophy_wealth_20k": "20,000",
	"lang": "English / 中文",
	"language": "语言",
	"lang_zh": "语言：中文",
	"lang_en": "Language: English",
	"cash": "现金",
	"stock": "股票",
	"day_frac": "第%d/8天",
	"end_day": "结束今天",
	"dusk_warn": "天快黑了",
	"buy_chick": "买鸡 %d",
	"sell_hen": "卖鸡 %d",
	"buy_share": "买入",
	"sell_share": "卖出",
	"eggs_count": "蛋 %d",
	"oven_max": "Lv.%d 已满",
	"oven_up": "%d 金币升级\n现在 Lv.%d",
	"gold_n": "金币  %d",
	"shares_n": "持有%d股",
	"price_cap": "股价",
	"hold_hint": "长按可连续操作",
	"baking": "烘焙中 %.1fs",
	"sell_cake_tip": "出售蛋糕，现有 %d 个",
	"cake_baking_tip": "蛋糕制作中",
	"news_hoard": "狼商囤粮",
	"news_cake": "蛋糕热销",
	"news_rain": "雨天减产",
	"tonight_news": "今夜告示 · %s",
	"quest_head": "农场任务",
	"quest_goal": "资产 3000，同时养 15 只鸡",
	"quest_done": "同一时刻双线达标",
	"quest_wealth": "总资产 %d / %d",
	"quest_flock": "拥有鸡 %d / %d",
	"quest_wealth_name": "总资产",
	"quest_flock_name": "拥有鸡",
	"quest_need_gold": "还差 %d",
	"quest_need_birds": "还差 %d 只",
	"quest_hit": "已达标",
	"quest_note": "两项要同时达到。资产掉下去或把鸡卖掉，完成会取消。",
	"quest_note_done": "三千金币和十五只鸡，同一时刻到手。",
	"continue_game": "继续游戏",
	"toast_dusk": "天快黑了，蛋会碎！",
	"toast_eggs_done": "今天的鸡蛋已经收完啦",
	"toast_no_chick": "还没有孵出来的小鸡",
	"toast_hatch_once": "每天只能孵 1 枚蛋",
	"toast_need_egg": "还差鸡蛋",
	"toast_hatching": "放进孵蛋器啦，明天出壳",
	"toast_no_cake": "还没有可出售的蛋糕",
	"toast_need_gold_share": "金币不够买入一股",
	"toast_no_shares": "还没有持股",
	"toast_need_gold_chick": "金币不够买小鸡",
	"toast_oven_short": "升级烤炉还差 %d 金币",
	"toast_oven_up": "烤炉升到 Lv.%d · 制作只需 %.1f 秒",
	"toast_no_hen": "还没有可以卖的母鸡",
	"toast_eggs_lost": "今天的蛋没有留到明天",
	"toast_no_rewind": "这一天没法重玩",
	"toast_no_gate_retry": "这个考核日的重试机会用过了",
	"toast_watching_ad": "正在招商…",
	"toast_rewound": "已重玩第 %d 天",
	"toast_quest": "双线达标！",
	"daily_title": "今日结算",
	"report_stats": "本日账目",
	"day_to_day": "第 %d 天  →  第 %d 天",
	"night_n": "第 %d 夜",
	"close_price": "收盘股价",
	"broken": "碎蛋",
	"grown": "长成",
	"cakes": "蛋糕",
	"wealth_gain": "增长",
	"wealth_loss": "缩水",
	"wealth_delta": "%+d",
	"wealth_flow": "总资产  %d  →  %d",
	"hatch_note": "新孵 %d 只，天亮后领取",
	"start_new_day": "开始新一天",
	"watch_ad": "看广告回到清晨",
	"finale_title": "八日总结",
	"finale_hook": "我在八日挑战里混成了",
	"rank_n": "第 %d / %d 等",
	"wealth_cap": "总资产",
	"flock_cap": "鸡群",
	"birds_n": "%d 只",
	"goal_n": "目标 %d",
	"goal_frac": "%d / %d",
	"goal_gap": "还差 %d",
	"goal_over": "多出 %d",
	"goal_over_gold": "多出 %d 金币",
	"goal_over_birds": "多出 %d 只鸡",
	"goal_gap_gold": "还差 %d 金币",
	"quest_stamp": "双线达标",
	"quest_miss": "未达标",
	"wealth_split": "现金 %d + 股票 %d",
	"chart_cap": "八日资产",
	"chart_goal": "目标 %d",
	"retry_eight": "再挑战八天",
	"continue_endless": "继续无尽模式",
	"share_card": "分享成绩",
	"share_saved": "已保存",
	"share_mark": "小鸡股市 · 敢不敢比",
	"toast_card_saved": "成绩图已保存，发到聊天里晒一下",
	"toast_card_fail": "图片没存下来，再试一次",
	"beat_daily": "你打败了 %s%% 的农场主。%s",
	"beat_finale": "八日收官，你打败了 %s%% 的挑战者。%s",
	"beat_challenge": "挑战通关，你打败了 %s%% 的农场主。%s",
	"beat_tail_0": "才刚进场，明天再捞。",
	"beat_tail_1": "超过了一小撮人。",
	"beat_tail_2": "有点东西了。",
	"beat_tail_3": "快摸到中位了。",
	"beat_tail_4": "太厉害了！",
	"beat_tail_5": "这局有点离谱。",
	"beat_tail_6": "这局封神了！",
	"rank_1_title": "流浪小鸡",
	"rank_1_copy": "八天空手而归。鸡：这人我都不认识。",
	"rank_2_title": "见习农民",
	"rank_2_copy": "刚摸到锄头，蛋还得自己捡。",
	"rank_3_title": "咯咯佃农",
	"rank_3_copy": "农场转了，钱包没转。",
	"rank_4_title": "篱笆鸡舍",
	"rank_4_copy": "篱笆围上了，蛋篓开始像样。",
	"rank_5_title": "积谷农户",
	"rank_5_copy": "谷仓有底，离顿顿吃饱还差一口。",
	"rank_6_title": "温饱农场",
	"rank_6_copy": "八日攒到三千，桌上终于能摆上热饭。",
	"rank_7_title": "街口商贩",
	"rank_7_copy": "四千二出手，邻居开始打听你。",
	"rank_8_title": "农场掌柜",
	"rank_8_copy": "五千二。鸡舍和股市两边都能转。",
	"rank_9_title": "金币大亨",
	"rank_9_copy": "六千五进袋，街坊开始叫你大亨。",
	"rank_10_title": "农场传奇",
	"rank_10_copy": "八千封顶。八日能摸到的最高等。",
	"rank_11_title": "农场街新贵",
	"rank_11_copy": "无尽里把家业推到一万三，街上换你的名。",
	"rank_12_title": "鸡隆·股斯克",
	"rank_12_copy": "一万八。鸡界本隆，股斯克本人。",
	# 奖励重试入口。文案必须描述真实发生的事：本轮没有真实广告，
	# 第一次是问卷，之后是五秒占位等待。不要写成「看广告」。
	"reward_survey_cta": "填反馈 → 重试今天",
	"reward_wait_cta": "等 5 秒 → 重试今天",
	"reward_wait_counting": "等待中… %d",
	"survey_title": "帮小鸡股市改进",
	"survey_intro": "选择题都要填；最后一题开放建议可空。答案只用于改进游戏和分组分析。",
	"survey_privacy": "不采集姓名、生日、联系方式或存档内容。",
	"survey_q_skill": "你觉得自己的游戏水平如何？",
	"survey_skill_novice": "新手／休闲",
	"survey_skill_intermediate": "进阶",
	"survey_skill_hardcore": "高手／硬核",
	"survey_q_age": "年龄范围",
	"survey_age_under18": "18 岁以下",
	"survey_age_18_24": "18–24",
	"survey_age_25_34": "25–34",
	"survey_age_35_plus": "35 岁以上",
	"survey_q_gender": "性别",
	"survey_gender_male": "男",
	"survey_gender_female": "女",
	"survey_gender_other": "其他",
	"survey_q_genre": "你玩过类似的经营／放置点击游戏吗？",
	"survey_genre_never": "从没玩过",
	"survey_genre_rarely": "几乎没玩过",
	"survey_genre_occasionally": "偶尔玩",
	"survey_genre_sometimes": "有时玩",
	"survey_genre_often": "经常玩",
	"survey_q_reason": "这次为什么想重试？",
	"survey_reason_rules": "没看懂规则",
	"survey_reason_too_slow": "来不及操作",
	"survey_reason_trade_regret": "买卖决策后悔了",
	"survey_reason_try_other": "想试另一种玩法",
	"survey_reason_misclick_lag": "误触或卡顿",
	"survey_reason_other": "其他",
	"survey_q_difficulty": "这一局的难度你觉得怎么样？",
	"survey_diff_too_easy": "太简单",
	"survey_diff_just_right": "刚刚好",
	"survey_diff_hard_fair": "有点难但公平",
	"survey_diff_too_hard": "太难了",
	"survey_diff_unclear": "不知道自己为什么没过",
	"survey_q_unclear": "哪一块最没看懂？",
	"survey_unclear_stock": "股价涨跌",
	"survey_unclear_bakery": "面包房",
	"survey_unclear_hatch": "孵蛋养鸡",
	"survey_unclear_timer": "一天的时间限制",
	"survey_unclear_goal": "过关目标",
	"survey_unclear_none": "都看懂了",
	"survey_q_stop": "这次不玩了的话，主要原因是？",
	"survey_stop_satisfied": "玩够了，挺满足",
	"survey_stop_too_hard": "太难，过不去",
	"survey_stop_repetitive": "重复，玩腻了",
	"survey_stop_boring": "前面太平淡",
	"survey_stop_lag": "卡顿或误触",
	"survey_stop_no_time": "只是没时间了",
	"survey_stop_other": "其他",
	"survey_q_ad": "如果不是等 5 秒，而是看一段 30 秒广告换重试，你还会换吗？",
	"survey_ad_yes": "会，随时都行",
	"survey_ad_stuck": "只在卡住的时候",
	"survey_ad_short": "更短一点才会",
	"survey_ad_no": "不会",
	"survey_q_free": "目前最希望改进什么？",
	"survey_free_hint": "一句话就好，不要填联系方式",
	"survey_undisclosed": "不想披露",
	"survey_submit": "提交",
	"survey_later": "以后再说",
	"survey_exit_title": "再说两句",
	"survey_exit_intro": "你已经填过画像那份了。这几题只问体验，选择题都要填；开放建议可空。",
	"survey_pulse_title": "走之前问一句",
	"survey_pulse_intro": "一题就好，选一个再提交。",
	"settings_feedback": "填写反馈问卷",
	"settings_feedback_more": "再说两句",
	"toast_survey_thanks": "谢谢，已收到",
	"toast_survey_done": "你已经填过了，谢谢",
	"survey_need_all": "还有题没选，请填完再提交",
}

const EN := {
	"challenge_goal": "Day %d close: %d wealth, %d birds",
	"challenge_ready": "Goals met for now. Checked at close.",
	"challenge_pending": "Meet both goals at the closing bell.",
	"challenge_rules": "This stage: %d seconds per day; chicks cost %d gold.",
	"challenge_summary": "Challenge Summary",
	"challenge_hook": "This challenge run",
	"challenge_chart": "Challenge wealth",
	"settings": "Settings",
	"font_size": "Text Size",
	"font_small": "Small",
	"font_standard": "Default",
	"font_large": "Large",
	"close": "Close",
	"sfx_on": "SFX: On",
	"sfx_off": "SFX: Off",
	"amb_on": "Ambience: On",
	"amb_off": "Ambience: Off",
	"sfx_title": "Sound Effects",
	"amb_title": "Ambient Sound",
	"toggle_on": "On",
	"toggle_off": "Off",
	"help": "Tap bubbles and buttons. Hold to collect, buy, or sell. 8-day challenge: 3000 wealth and 15 birds at once.",
	"credits": "Contact: hhhhhhnicaia@gmail.com",
	"restart": "Reset Game",
	"home_menu": "Main Menu",
	"tutorial_replay": "Replay Tutorial",
	"guide": "Quick Guide",
	"guide_title": "Chicken Market · One-Day Primer",
	"guide_subtitle": "Learn the farm and the market in one sitting",
	"guide_step_eggs": "1  Collect Eggs",
	"guide_step_eggs_desc": "Hens lay on their own clock. When an egg appears, tap the bubble to collect it.",
	"guide_step_chick": "2  Hatch and Bake",
	"guide_step_chick_desc": "At most one egg goes in the nest each day and hatches tomorrow. Two eggs bake into a cake worth 150 gold.",
	"guide_step_stock": "3  Hens and Stocks",
	"guide_step_stock_desc": "A hen costs 50 and lays starting tomorrow. Spare gold can buy stock; the price moves each day. Sell higher than you bought to profit. Hit 3000 gold and 15 birds in 8 days.",
	"tutorial_header": "One-Day Primer",
	"tutorial_day_frac": "Lesson",
	"tutorial_exit": "Exit Tutorial",
	"tutorial_begin": "Start",
	"tutorial_continue": "Continue",
	"tutorial_finish": "Start the Real Game",
	"tutorial_t0_goal": "Goal: reach 3000 gold and 15 birds within 8 days. Time is paused during the lesson.",
	"tutorial_t1_eggs": "Hens lay eggs, but not on a fixed timer. When one appears, tap the bubble. (%d/3)",
	"tutorial_t1_eggs_landing": "The eggs are flying to the basket. Wait a moment. (%d/3)",
	"tutorial_t2_hatch": "You can nest at most 1 egg per day. It hatches into a chick tomorrow. Tap hatch.",
	"tutorial_t3_cake_wait": "The other 2 eggs bake into a cake automatically. Wait for it.",
	"tutorial_t3_cake_sell": "Tap the cake to turn it into 150 gold.",
	"tutorial_t4_hen": "Spend 50 gold to buy a hen. She only starts laying tomorrow.",
	"tutorial_t5_buy": "Spare gold can buy stock. The price moves at random each day. Buy 1 share.",
	"tutorial_t6_sell": "Pretend a night passed: the price rose from 120 to 150. Sell higher than you bought to profit.",
	"tutorial_t7_done": "Collect, hatch, bake, buy hens, trade stock. Now go hit the 8-day goal.",
	"tutorial_tap_hint": "Tap the gold pulsing target.",
	"tutorial_locked_hint": "The other actions unlock next.",
	"tutorial_exit_toast": "Tutorial closed.",
	"tutorial_complete_toast": "Primer done! The real 8-day challenge begins.",
	"start_pick": "Pick a start",
	"start_tutorial": "Tutorial",
	"start_direct": "Start Game",
	"start_challenge": "Challenge",
	"start_endless": "Endless",
	"toast_lock_challenge": "Finish the 8-day close first.",
	"toast_lock_endless": "Clear Challenge day 20 first.",
	"you_win": "YOU WIN",
	"back_menu": "Menu",
	"enter_challenge": "Enter Challenge",
	"retry_challenge": "Retry Challenge",
	"challenge_flop_copy": "Missed the day %d gate.",
	"campaign_flop_copy": "Missed the 8-day goal: 3000 gold and 15 birds.",
	"start_settings": "Settings",
	"start_trophies": "Trophies",
	"day_endless": "Day %d",
	"trophy_title": "Trophies",
	"trophy_locked": "Locked",
	"toast_trophy": "Trophy: %s",
	"trophy_primer": "One-Day Primer",
	"trophy_primer_desc": "Finish collect, hatch, bake, and trade.",
	"trophy_cake": "First Cake",
	"trophy_cake_desc": "Sell a baked cake for gold.",
	"trophy_hen": "Coop Open",
	"trophy_hen_desc": "Buy your first hen from the wolf.",
	"trophy_share": "First Trade",
	"trophy_share_desc": "Buy your first share.",
	"trophy_rank_day8_desc": "Hit %d wealth at the 8-day close.",
	"trophy_rank_endless_desc": "Hit %d wealth in Endless.",
	"trophy_flock": "Fifteen Birds",
	"trophy_flock_desc": "Hold 15 birds at once.",
	"trophy_day8": "Eight-Day Close",
	"trophy_day8_desc": "Finish an 8-day challenge.",
	"trophy_endless7": "Endless Seven",
	"trophy_endless7_desc": "Reach day 7 in Endless.",
	"trophy_chicken_king": "Chicken King",
	"trophy_chicken_king_desc": "Hold 100 birds at once.",
	"trophy_chicken_emperor": "Chicken Emperor",
	"trophy_chicken_emperor_desc": "Hold 200 birds at once.",
	"trophy_retail": "Retail Isn't Chives",
	"trophy_retail_desc": "Make 2000 from stocks in one run.",
	"trophy_stock_god": "Stock God",
	"trophy_stock_god_desc": "Make 3000 from stocks in one run.",
	"trophy_wealth_tier_desc": "Clear Challenge with %d wealth.",
	"trophy_wealth_100k": "Seal Clucklon Musk",
	"trophy_wealth_90k": "90,000",
	"trophy_wealth_80k": "Chicken Buffett",
	"trophy_wealth_70k": "70,000",
	"trophy_wealth_60k": "60,000",
	"trophy_wealth_50k": "50,000",
	"trophy_wealth_40k": "40,000",
	"trophy_wealth_30k": "30,000",
	"trophy_wealth_20k": "20,000",
	"lang": "English / 中文",
	"language": "Language",
	"lang_zh": "语言：中文",
	"lang_en": "Language: English",
	"cash": "Cash",
	"stock": "Stocks",
	"day_frac": "Day %d/8",
	"end_day": "End Today",
	"dusk_warn": "Night falling",
	"buy_chick": "Buy chick %d",
	"sell_hen": "Sell hen %d",
	"buy_share": "Buy",
	"sell_share": "Sell",
	"eggs_count": "Eggs %d",
	"oven_max": "Lv.%d max",
	"oven_up": "%d gold\nNow Lv.%d",
	"gold_n": "Gold  %d",
	"shares_n": "Holding %d",
	"price_cap": "Price",
	"hold_hint": "Hold to repeat",
	"baking": "Baking %.1fs",
	"sell_cake_tip": "Sell cakes (%d)",
	"cake_baking_tip": "Cake in the oven",
	"news_hoard": "Wolf hoards",
	"news_cake": "Cake boom",
	"news_rain": "Rain cut",
	"tonight_news": "Tonight · %s",
	"quest_head": "Farm Quest",
	"quest_goal": "Hit 3000 wealth and 15 birds at the same time",
	"quest_done": "Both goals met",
	"quest_wealth": "Wealth %d / %d",
	"quest_flock": "Birds %d / %d",
	"quest_wealth_name": "Wealth",
	"quest_flock_name": "Birds",
	"quest_need_gold": "%d to go",
	"quest_need_birds": "%d birds to go",
	"quest_hit": "Done",
	"quest_note": "Both must be true at the same time. Selling birds or losing wealth undoes it.",
	"quest_note_done": "3000 gold and 15 birds, held together.",
	"continue_game": "Continue",
	"toast_dusk": "Night is falling — eggs will spoil!",
	"toast_eggs_done": "No more eggs today",
	"toast_no_chick": "No chicks have hatched yet",
	"toast_hatch_once": "Only 1 egg can hatch per day",
	"toast_need_egg": "Need an egg first",
	"toast_hatching": "In the incubator — hatches tomorrow",
	"toast_no_cake": "No cakes to sell",
	"toast_need_gold_share": "Not enough gold for a share",
	"toast_no_shares": "You don't hold any shares",
	"toast_need_gold_chick": "Not enough gold for a chick",
	"toast_oven_short": "Need %d more gold to upgrade",
	"toast_oven_up": "Oven Lv.%d · bakes in %.1fs",
	"toast_no_hen": "No hens to sell",
	"toast_eggs_lost": "Today's eggs didn't last the night",
	"toast_no_rewind": "Can't rewind this day",
	"toast_no_gate_retry": "This gate's retry is already used",
	"toast_watching_ad": "Ads coming soon…",
	"toast_rewound": "Rewound to day %d",
	"toast_quest": "Both goals hit!",
	"daily_title": "Daily Close",
	"report_stats": "Today",
	"day_to_day": "Day %d → %d",
	"night_n": "Night %d",
	"close_price": "Close",
	"broken": "Break",
	"grown": "Grown",
	"cakes": "Cake",
	"wealth_gain": "Gain",
	"wealth_loss": "Loss",
	"wealth_delta": "%+d",
	"wealth_flow": "Wealth  %d → %d",
	"hatch_note": "%d hatched · collect at dawn",
	"start_new_day": "Start new day",
	"watch_ad": "Ad → rewind to dawn",
	"finale_title": "8-Day Summary",
	"finale_hook": "My 8-day rank:",
	"rank_n": "Rank %d / %d",
	"wealth_cap": "Wealth",
	"flock_cap": "Flock",
	"birds_n": "%d birds",
	"goal_n": "Goal %d",
	"goal_frac": "%d / %d",
	"goal_gap": "%d short",
	"goal_over": "+%d",
	"goal_over_gold": "+%d gold",
	"goal_over_birds": "+%d birds",
	"goal_gap_gold": "%d gold short",
	"quest_stamp": "Both goals hit",
	"quest_miss": "Not cleared",
	"wealth_split": "Cash %d + Stock %d",
	"chart_cap": "8-day wealth",
	"chart_goal": "Goal %d",
	"retry_eight": "Try 8 days again",
	"continue_endless": "Continue Endless",
	"share_card": "Share",
	"share_saved": "Saved",
	"share_mark": "Chick Street · beat me",
	"toast_card_saved": "Card saved. Post it.",
	"toast_card_fail": "Couldn't save. Try again.",
	"beat_daily": "You beat %s%% of farms. %s",
	"beat_finale": "Eight-day close: you beat %s%% of challengers. %s",
	"beat_challenge": "Challenge clear: you beat %s%% of ranchers. %s",
	"beat_tail_0": "Just getting started.",
	"beat_tail_1": "A sliver ahead.",
	"beat_tail_2": "Not bad at all.",
	"beat_tail_3": "Almost at the median.",
	"beat_tail_4": "That's strong!",
	"beat_tail_5": "This run is wild.",
	"beat_tail_6": "This run is cracked!",
	"rank_1_title": "Stray Chick",
	"rank_1_copy": "Eight days. Empty pockets. The hens don't know you.",
	"rank_2_title": "Apprentice Farmer",
	"rank_2_copy": "Just found the hoe. Still picking eggs yourself.",
	"rank_3_title": "Cluck Tenant",
	"rank_3_copy": "Farm's running. Wallet isn't.",
	"rank_4_title": "Fence Coop",
	"rank_4_copy": "Fence is up. The egg basket looks real.",
	"rank_5_title": "Grain Farmer",
	"rank_5_copy": "The barn has a floor. Full meals are still a bite away.",
	"rank_6_title": "Full-Belly Farm",
	"rank_6_copy": "Three thousand in eight days. Dinner is hot.",
	"rank_7_title": "Corner Vendor",
	"rank_7_copy": "Forty-two hundred. Neighbors started asking.",
	"rank_8_title": "Farm Keeper",
	"rank_8_copy": "Fifty-two hundred. Coop and market both run.",
	"rank_9_title": "Gold Baron",
	"rank_9_copy": "Sixty-five hundred. They started calling you baron.",
	"rank_10_title": "Farm Legend",
	"rank_10_copy": "Eight thousand. The top of the eight-day climb.",
	"rank_11_title": "Farm Street Star",
	"rank_11_copy": "Thirteen thousand in Endless. The street says your name.",
	"rank_12_title": "Clucklon Musk",
	"rank_12_copy": "Eighteen thousand. Clucklon Musk of Chicken Street.",
	"reward_survey_cta": "Feedback → retry today",
	"reward_wait_cta": "Wait 5s → retry today",
	"reward_wait_counting": "Waiting… %d",
	"survey_title": "Help us improve",
	"survey_intro": "Choice questions are required; the last open question is optional. Answers only shape the game and group the data.",
	"survey_privacy": "No name, birthday, contact details or save data is collected.",
	"survey_q_skill": "How would you rate your gaming skill?",
	"survey_skill_novice": "New / casual",
	"survey_skill_intermediate": "Intermediate",
	"survey_skill_hardcore": "Skilled / hardcore",
	"survey_q_age": "Age range",
	"survey_age_under18": "Under 18",
	"survey_age_18_24": "18–24",
	"survey_age_25_34": "25–34",
	"survey_age_35_plus": "35+",
	"survey_q_gender": "Gender",
	"survey_gender_male": "Male",
	"survey_gender_female": "Female",
	"survey_gender_other": "Other",
	"survey_q_genre": "Played similar tycoon / idle-clicker games?",
	"survey_genre_never": "Never",
	"survey_genre_rarely": "Almost never",
	"survey_genre_occasionally": "Occasionally",
	"survey_genre_sometimes": "Sometimes",
	"survey_genre_often": "Often",
	"survey_q_reason": "Why retry this day?",
	"survey_reason_rules": "Didn't get the rules",
	"survey_reason_too_slow": "Ran out of time",
	"survey_reason_trade_regret": "Regretted a trade",
	"survey_reason_try_other": "Wanted another approach",
	"survey_reason_misclick_lag": "Misclick or lag",
	"survey_reason_other": "Other",
	"survey_q_difficulty": "How did this run feel?",
	"survey_diff_too_easy": "Too easy",
	"survey_diff_just_right": "About right",
	"survey_diff_hard_fair": "Hard but fair",
	"survey_diff_too_hard": "Too hard",
	"survey_diff_unclear": "Not sure why I lost",
	"survey_q_unclear": "Which part made least sense?",
	"survey_unclear_stock": "Share price",
	"survey_unclear_bakery": "Bakery",
	"survey_unclear_hatch": "Hatching chicks",
	"survey_unclear_timer": "The day timer",
	"survey_unclear_goal": "The goal to clear",
	"survey_unclear_none": "All of it was clear",
	"survey_q_stop": "If you are stopping now, the main reason is?",
	"survey_stop_satisfied": "Had my fill — satisfied",
	"survey_stop_too_hard": "Too hard to get past",
	"survey_stop_repetitive": "Too repetitive",
	"survey_stop_boring": "Slow at the start",
	"survey_stop_lag": "Lag or misclicks",
	"survey_stop_no_time": "Just out of time",
	"survey_stop_other": "Other",
	"survey_q_ad": "If the retry cost a 30-second ad instead of a 5-second wait, would you still take it?",
	"survey_ad_yes": "Yes, any time",
	"survey_ad_stuck": "Only when stuck",
	"survey_ad_short": "Only if shorter",
	"survey_ad_no": "No",
	"survey_q_free": "What would you most like improved?",
	"survey_free_hint": "One line is plenty — no contact details",
	"survey_undisclosed": "Prefer not to say",
	"survey_submit": "Submit",
	"survey_later": "Maybe later",
	"survey_exit_title": "One more round of questions",
	"survey_exit_intro": "You already did the profile one. These are about how it felt — choice questions required; open note optional.",
	"survey_pulse_title": "One quick question",
	"survey_pulse_intro": "Just one — pick an option, then submit.",
	"settings_feedback": "Send feedback",
	"settings_feedback_more": "Say a bit more",
	"toast_survey_thanks": "Thanks — got it",
	"toast_survey_done": "You've already sent it — thanks",
	"survey_need_all": "Please answer every choice question before submitting",
}

static func t(key: String, args: Array = []) -> String:
	if not _booted:
		_booted = true
		load_settings()
	var table: Dictionary = EN if lang == "en" else ZH
	var s := str(table.get(key, ZH.get(key, key)))
	if args.is_empty():
		return s
	return s % args

static func news(id: String) -> String:
	return t("news_%s" % id)

static func rank_title(lv: int) -> String:
	return t("rank_%d_title" % clampi(lv, 1, 12))

static func rank_copy(lv: int) -> String:
	return t("rank_%d_copy" % clampi(lv, 1, 12))

static func toggle() -> void:
	set_lang("en" if lang == "zh" else "zh")

static func set_lang(next: String) -> bool:
	if next != "zh" and next != "en":
		return false
	if lang == next:
		return false
	var now := Time.get_ticks_msec()
	if now - _toggle_ms < 280:
		return false
	_toggle_ms = now
	lang = next
	save()
	return true

static func load_settings() -> void:
	if not FileAccess.file_exists(SETTINGS_PATH):
		return
	var f := FileAccess.open(SETTINGS_PATH, FileAccess.READ)
	if f == null:
		return
	var parsed = JSON.parse_string(f.get_as_text())
	if typeof(parsed) != TYPE_DICTIONARY:
		return
	var next := str(parsed.get("lang", lang))
	if next == "en" or next == "zh":
		lang = next
	ui_font_scale = 0.85

static func set_ui_font_scale(value: float) -> void:
	ui_font_scale = clampf(value, 0.85, 1.15)
	save()

static func save() -> void:
	var f := FileAccess.open(SETTINGS_PATH, FileAccess.WRITE)
	if f:
		f.store_string(JSON.stringify({"lang": lang, "ui_font_scale": ui_font_scale}))
